# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#

jobs:
  - job:
    displayName: Build BICEP
    steps:
      - task: CopyFiles@2
        displayName: Copy bicep files
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)
          Contents: |
            **\bicep\**
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: $(Build.DefinitionName)
          publishLocation: Container
