# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#

jobs:
  - job:
    displayName: Build API
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: $(System.DefaultWorkingDirectory)/**/*.csproj
      - task: DotNetCoreCLI@2
        displayName: Build project
        inputs:
          command: build
          projects: $(System.DefaultWorkingDirectory)/**/*.csproj
          arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release
      - script: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations script -p $(System.DefaultWorkingDirectory)/back/LEL.Resume.Api/LEL.Resume.Api.csproj -c LEL.Resume.Api.Data.DefaultDbContext -o Migration.sql -i -v
        displayName: Build migration
      - task: CopyFiles@2
        displayName: Copy migration file
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)
          Contents: |
            **\*.sql
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - task: ArchiveFiles@2
        displayName: Archive files
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)/publish_output
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/api/$(Build.BuildId).zip
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: $(Build.DefinitionName)
          publishLocation: Container
